### ISSUE TITLE
On RPi4 running "make build" (usnuported architecture)

### ISSUE THREAD

**Issue by mmatesic01** [oofnikj/docker-openwrt#20]
HI Runing latest Rasspbery lite OS on RPi4 2GB.

I have configured the file openwrt.conf with ARCH=armvirt-32
When I start "make build" I get this error:
_./build.sh
./build.sh: 29: ./build.sh: [[: not found
./build.sh: 34: ./build.sh: [[: not found
./build.sh: 37: ./build.sh: [[: not found
./build.sh: 40: ./build.sh: [[: not found
Unsupported architecture!
./build.sh: 71: ./build.sh: [[: not found
make: *** [Makefile:7: build] Error 1_

Also when I do to this:
docker pull oofnik/openwrt:19.07.5-armvirt-32
docker run oofnik/openwrt:19.07.5-armvirt-32
I get also message:
_WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
Failed to send flush request: Operation not permitted
RTNETLINK answers: Operation not permitted_

Any advice here?
Thank you.

**Comment by mmatesic01** [comment]
typing "[[" and "]]" in all sh scripts has to be in "[" and  "]". Then it works.

**Comment by oofnikj** [comment]
Hi, thanks for opening this. I did not test the build script on Raspberry Pi OS since making some changes. I will do some testing and incorporate your suggestions.

The message you see when pulling and running the image directly is expected. The OpenWrt image is not meant to be run interactively; furthermore, it is not built as a multi-arch image, so this architecture warning appears despite containing binaries compiled for ARM.

There is some discussion about the interactive container behavior on the [OpenWrt forums](https://forum.openwrt.org/t/running-openwrt-in-a-docker-container/56049/6).
